### ISSUE TITLE
IE11 toggle Group button open/closes accordion

### ISSUE THREAD

**Issue by Martin-Welte** [towa-digital/towa-gdpr-plugin#15]
**Describe the bug**
In internet explorer 11 the toggle group button opens/closes the accordion as well. 

**To Reproduce**
- Use IE 11 
- toggle cookie group

**Expected behavior**
Only the group should be activated/deactivated and the accordion functionality only controlled via the open/close button

**Desktop:**
 - IE 11

**Comment by szepeviktor** [comment]
Those bubbling events!

**Comment by SahinU88** [comment]
We will stop the maintenance of this in the near future, thus we don't look at requests.

Sry for this one.
