### ISSUE TITLE
Generated code in the repo

### ISSUE THREAD

**Issue by szepeviktor** [towa-digital/towa-gdpr-plugin#3]
Please consider putting only source code in the repo.

A build process could handle the plugin release: run tests and build all part, e.g. compile SASS to CSS

Was https://bitbucket.org/towa_gmbh/towa-gdpr-plugin/issues/2/generated-code-in-the-repo
@Martin-Welte

**Comment by SahinU88** [comment]
We will stop the maintenance of this in the near future, thus we don't look at requests.

Sry for this one.
