### ISSUE TITLE
Modern coding standard

### ISSUE THREAD

**Issue by szepeviktor** [towa-digital/towa-gdpr-plugin#4]
https://github.com/szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset

Here I’m trying to gain benefits of

- livable and readable PSR-12
- Automattic’s Neutron power 😀
- and static analysis from WPCS
- Slevomat 🚀 rules

Was https://bitbucket.org/towa_gmbh/towa-gdpr-plugin/issues/3/modern-coding-standard

**Comment by SahinU88** [comment]
We will stop the maintenance of this in the near future, thus we don't look at requests.

Sry for this one.
